version: '3.8'

services:
  # 1. The Message Broker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. The Django API Server
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Syncs your local code edits instantly without rebuilding
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - redis

  # 3. The Celery Worker
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock # CRITICAL: The Docker Socket
    env_file:
      - .env
    depends_on:
      - redis
      - web