# Generated by Django 5.2.12 on 2026-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='problem',
            name='input_type',
            field=models.CharField(choices=[('two_ints', 'Two Integers (a, b)'), ('array_int', 'Array of Integers'), ('two_arrays', 'Two Arrays of Integers'), ('string', 'Single String'), ('int', 'Single Integer'), ('array_target', 'Array + Target Integer')], default='two_ints', help_text='How the judge parses input_data and calls solve()', max_length=30),
        ),
        migrations.AlterField(
            model_name='problem',
            name='boilerplate_code',
            field=models.TextField(blank=True, help_text='Starter template shown in the editor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error')], default='P', max_length=30),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='input_data',
            field=models.TextField(help_text="Raw input matching the problem's input_type"),
        ),
    ]
