# Generated by Django 5.2.12 on 2026-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_problem_template_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='template_code',
        ),
        migrations.AddField(
            model_name='problem',
            name='templates',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of language-specific boilerplates'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='boilerplate_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_type',
            field=models.CharField(choices=[('two_ints', 'Two Integers (a, b)'), ('array_int', 'Array of Integers'), ('two_arrays', 'Two Arrays of Integers'), ('string', 'Single String'), ('int', 'Single Integer'), ('array_target', 'Array + Target Integer')], default='two_ints', max_length=30),
        ),
    ]
