# Generated by Django 5.2.12 on 2026-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_remove_problem_template_code_problem_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='acceptance_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='problem',
            name='asked_by_faang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='related_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
