# Generated by Django 5.2.12 on 2026-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_problem_acceptance_rate_problem_asked_by_faang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='companies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='related_topics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='templates',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of language-specific boilerplates', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
